/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.files.jsonc --include-runtime=false --env-interface=FilesEnv files-worker-configuration.d.ts` (hash: 97bc16a3823997d4fef0fb12c2c9ec41)
interface __BaseEnv_FilesEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/files/index");
	}
	interface Env extends __BaseEnv_FilesEnv {}
}
interface FilesEnv extends __BaseEnv_FilesEnv {}
