/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.files.jsonc --include-runtime=false --env-interface=FilesEnv files-worker-configuration.d.ts` (hash: edded0c1364182c27b0c5b5fa5c084ab)
interface __BaseEnv_FilesEnv {
	HTML_BLOCKS: R2Bucket;
	ASSETS: Fetcher;
	FILES_URL_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/files/index");
	}
	interface StagingEnv {
		HTML_BLOCKS: R2Bucket;
		ASSETS: Fetcher;
		FILES_URL_SECRET: string;
	}
	interface ProductionEnv {
		HTML_BLOCKS: R2Bucket;
		ASSETS: Fetcher;
		FILES_URL_SECRET: string;
	}
	interface Env extends __BaseEnv_FilesEnv {}
}
interface FilesEnv extends __BaseEnv_FilesEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FILES_URL_SECRET">> {}
}
